[package]
name = "glisp"
version = "0.1.0"
authors = ["hideki kuno <hidekuno@gmail.com>"]
edition = "2018"

[dependencies]
elisp = { path = "../elisp" }
gtk = "0.7.0"
glib = "0.8.1"
gdk = "0.11.0"
cairo-rs = { version = "0.7.1", features = ["png"] }

[features]
animation = []
