[package]
name = "elisp"
version = "0.7.2"
authors = ["hideki kuno <hidekuno@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
log = "*"
env_logger = "*"
rand = "0.6"

[features]
thread = []