[package]
name = "weblisp"
version = "0.8.4"
authors = ["hidekuno <hidekuno@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
elisp = { path = "../elisp", version = "0.8.4", features = ["thread"] }
log = "*"
env_logger = "*"

[features]
all-interface = []
